### ISSUE TITLE
Design Tweaks Broke WotLK

### ISSUE THREAD

**Issue by ManneN1** [Stanzilla/BindPad#10]
The recent design tweak commit broke the addon partly on WotLK.

If the intention is that there should be 7 icons per row instead of 6, this is not working. It ends up looking as follows:

Prior:
![image](https://user-images.githubusercontent.com/16864855/222985062-3019bb9c-8ccb-4148-b680-53659f6c9cc3.png)
After:
![image](https://user-images.githubusercontent.com/16864855/222984655-0fe467f5-1136-45fa-8698-bb5334104fc2.png)

Where A4 and A8 are mysteriously gone and everything is shuffled around substantially. New macros named A4 and A8 can however not be created because they still exist, so it's a semi-brick unless the user decides to flush the wtf file.

**Comment by Stanzilla** [comment]
Thanks, fixed!
