### ISSUE TITLE
Doesn't work in SoD.

### ISSUE THREAD

**Issue by dukenukemx** [Stanzilla/BindPad#13]
New SoD came out and completely broke Bindpad.

**Comment by dukenukemx** [comment]
Here's how it looks like when you open up Bindpad in SoD. 

![bindpad](https://github.com/user-attachments/assets/249e76cd-6723-426c-a6f9-85e44486c425)

**Comment by Swarfimus** [comment]
Broken now in 11.0

**Comment by Stanzilla** [comment]
Not going to support SoD until they have the same API as the other clients, sorry

**Comment by nymann** [comment]
I added support for this in my fork for classic anniversary https://github.com/nymann/BindPad but I'll wait with submitting a PR until I have used it myself for a bit.
