### ISSUE TITLE
Broken in 11.0

### ISSUE THREAD

**Issue by Swarfimus** [Stanzilla/BindPad#14]
Hoping for a fix, and I can't play without this addon.

**Comment by Ayeager77** [comment]
Agreed.

**Comment by Ayeager77** [comment]
It is still broken despite the patch an hour ago

**Comment by Stanzilla** [comment]
> It is still broken despite the patch an hour ago

you need to post more info then, which errors are you getting?

**Comment by Ayeager77** [comment]
Apologies, I was just reacting to you closing it. I'm, gathering it now:

https://1drv.ms/t/s!AtVq8xPtTL5OipQeMbvVnbNorlet7Q?e=F200Xt

**Comment by Stanzilla** [comment]
> Apologies, I was just reacting to you closing it. I'm, gathering it now:
> 
> [1drv.ms/t/s!AtVq8xPtTL5OipQeMbvVnbNorlet7Q?e=F200Xt](https://1drv.ms/t/s!AtVq8xPtTL5OipQeMbvVnbNorlet7Q?e=F200Xt)

are you on Cata?

**Comment by Ayeager77** [comment]
Yes

**Comment by Stanzilla** [comment]
> Yes

Why are you posting in a ticket about retail 11 then? :D

**Comment by Ayeager77** [comment]
and I just realized this is probably the reporting for Retail. My mistake for not paying attention. I can go to the proper forum.

**Comment by Ayeager77** [comment]
Again, my apologies. I was not paying attention. Thank you for your time.

**Comment by Swarfimus** [comment]
@Stanzilla Hi friend, sorry for my late reply here.  I'm the one who originally opened the thread.  It seems the addon updated through Curse and at first glance appears to be working now.  I just wanted to post briefly and thank you for your time.  Thank you.
