### ISSUE TITLE
Cata issues after recent update

### ISSUE THREAD

**Issue by Ayeager77** [Stanzilla/BindPad#15]
After recent update (couple hours ago) I am getting errors in Cata for:

https://1drv.ms/t/s!AtVq8xPtTL5OipQeMbvVnbNorlet7Q?e=F200Xt

**Comment by Stanzilla** [comment]
Fixed in 2.9.15

**Comment by Ayeager77** [comment]
Again, TYVM. I appreciate your work on this addon and WA's
