### ISSUE TITLE
BP Repeated local (error ) in Cata

### ISSUE THREAD

**Issue by Ayeager77** [Stanzilla/BindPad#18]
2830x BindPad/BindPad.lua:2129: attempt to call field 'GetSpellName' (a nil value)
[string "@BindPad/BindPad.lua"]:2129: in function `GetActionCommand'
[string "@BindPad/BindPad.lua"]:1963: in function <BindPad/BindPad.lua:1962>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetAction'
[string "@ElvUI_Libraries/Core/LibActionButton-1.0/LibActionButton-1.0.lua"]:2689: in function `SetTooltip'
[string "@ElvUI_Libraries/Core/LibActionButton-1.0/LibActionButton-1.0.lua"]:2393: in function <...ies/Core/LibActionButton-1.0/LibActionButton-1.0.lua:2385>
[string "@ElvUI_Libraries/Core/LibActionButton-1.0/LibActionButton-1.0.lua"]:1254: in function <...ies/Core/LibActionButton-1.0/LibActionButton-1.0.lua:1252>
[string "=(tail call)"]: ?
[string "=[C]"]: ?

Locals:
actionSlot = 15
type = "spell"
id = 16689
subType = "spell"
subSubType = nil
(*temporary) = <function> defined @BindPad/BindPad.lua:13
(*temporary) = "SPELL "
(*temporary) = nil
(*temporary) = 16689
(*temporary) = "attempt to call field 'GetSpellName' (a nil value)"
concat = <function> defined @BindPad/BindPad.lua:13
GetItemInfo = <function> defined =[C]:-1

******
Cata version. Even with Elvui and all plugins disabled, all keybinds in BP cleared, and a full reload of the game client, I get this error on multiple characters. No matter if I'm simply standing in an Inn or in combat.

I've now gone as far as to delete my WTF, turn off all Addons except BP and I get:

******

Message: Interface/AddOns/BindPad/BindPad.lua:2129: attempt to call field 'GetSpellName' (a nil value)
Time: Sat Aug 10 21:04:14 2024
Count: 2
Stack: Interface/AddOns/BindPad/BindPad.lua:2129: attempt to call field 'GetSpellName' (a nil value)
[string "@Interface/AddOns/BindPad/BindPad.lua"]:2129: in function `GetActionCommand'
[string "@Interface/AddOns/BindPad/BindPad.lua"]:1963: in function <Interface/AddOns/BindPad/BindPad.lua:1962>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `SetAction'
[string "@Interface/AddOns/Blizzard_ActionBar/Classic/ActionButton.lua"]:815: in function `ActionButton_SetTooltip'
[string "*ActionBarFrame.xml:37_OnEnter"]:5: in function <[string "*ActionBarFrame.xml:37_OnEnter"]:1>

Locals: actionSlot = 58
type = "spell"
id = 25780
subType = "spell"
subSubType = nil
(*temporary) = <function> defined @Interface/AddOns/BindPad/BindPad.lua:13
(*temporary) = "SPELL "
(*temporary) = nil
(*temporary) = 25780
(*temporary) = "attempt to call field 'GetSpellName' (a nil value)"
concat = <function> defined @Interface/AddOns/BindPad/BindPad.lua:13
GetItemInfo = <function> defined =[C]:-1

**Comment by Stanzilla** [comment]
Should be fixed now
