### ISSUE TITLE
we

### ISSUE THREAD

**Issue by XyzKangUI** [Stanzilla/BindPad#21]
https://github.com/Stanzilla/BindPad/blob/0d936d1588412eca2815373a0d125ce5f144e142/BindPad/BindPad.lua#L85

https://warcraft.wiki.gg/wiki/API_C_Container.GetContainerItemID

**Comment by Stanzilla** [comment]
what are you suggesting?

**Comment by XyzKangUI** [comment]
> what are you suggesting?

C_Item has to be C_Container

**Comment by Stanzilla** [comment]
ah, thank you
