### ISSUE TITLE
Error report

### ISSUE THREAD

**Issue by ChumBombarda** [Stanzilla/BindPad#24]
Message: Interface/AddOns/BindPad/BindPad.lua:1341: attempt to call global 'HasPetSpells' (a nil value)
Time: Sun Aug 25 02:19:23 2024
Count: 1
Stack: Interface/AddOns/BindPad/BindPad.lua:1341: attempt to call global 'HasPetSpells' (a nil value)
[string "=[C]"]: in function `HasPetSpells'
[string "@Interface/AddOns/BindPad/BindPad.lua"]:1341: in function `GetSpellNum'
[string "@Interface/AddOns/BindPad/BindPad.lua"]:2360: in function `GetBaseForMorphingSpell'
[string "@Interface/AddOns/BindPad/BindPad.lua"]:2140: in function `OverwriteHotKey'
[string "@Interface/AddOns/BindPad/BindPad.lua"]:2119: in function <Interface/AddOns/BindPad/BindPad.lua:2115>

Locals:

**Comment by TheDescender** [comment]
Seconding this, same Lua Error.

Message: Interface/AddOns/BindPad/BindPad.lua:1341: attempt to call global 'HasPetSpells' (a nil value)
Time: Tue Aug 27 01:21:10 2024
Count: 7
Stack: Interface/AddOns/BindPad/BindPad.lua:1341: attempt to call global 'HasPetSpells' (a nil value)
[string "@Interface/AddOns/BindPad/BindPad.lua"]:1341: in function `GetSpellNum'
[string "@Interface/AddOns/BindPad/BindPad.lua"]:2360: in function `GetBaseForMorphingSpell'
[string "@Interface/AddOns/BindPad/BindPad.lua"]:2140: in function `OverwriteHotKey'
[string "@Interface/AddOns/BindPad/BindPad.lua"]:2119: in function <Interface/AddOns/BindPad/BindPad.lua:2115>

Locals: bookType = nil
spellNum = nil
(*temporary) = nil
(*temporary) = "attempt to call global 'HasPetSpells' (a nil value)
