### ISSUE TITLE
Error when mousing over bag slots

### ISSUE THREAD

**Issue by teyasio** [Stanzilla/BindPad#8]
17x Interface/AddOns/BindPad/BindPad.lua:1935: attempt to call global 'GetContainerItemID' (a nil value)
[string "@Interface/AddOns/BindPad/BindPad.lua"]:1935: in function <Interface/AddOns/BindPad/BindPad.lua:1934>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `SetBagItem'
[string "@Interface/FrameXML/ContainerFrame.lua"]:1503: in function `OnUpdate'
[string "@Interface/FrameXML/ContainerFrame.lua"]:1470: in function `OnEnter'
[string "@Interface/FrameXML/ContainerFrame.lua"]:1466: in function <Interface/FrameXML/ContainerFrame.lua:1465>

Locals:
self = GameTooltip {
 0 = <userdata>
 SetQuestLogRewardSpell = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:439
 SetQuestPartyProgress = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:439
 hasMoney = 1
 ProcessLineData = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:298
 shownMoneyFrames = 1
 numMoneyFrames = 1
 info = <table> {
 }
 SetPvpTalent = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:439
 SetRuneforgeResultItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:439
 SetHyperlink = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:439
 SetUnit = <function> defined =[C]:-1
 SetAzeriteEssence = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:439
 SetVoidDepositItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:439
 SetVoidWithdrawalItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:439
 waitingForData = false
 OnLoad = <function> defined @Interface/FrameXML/GameTooltip.lua:916
 SetInfoBackdropStyle = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:333
 shoppingTooltips = <table> {
 }
 SetSocketGem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:439
 updateTooltipTimer = 0.043000
 ItemTooltip = Frame {
 }
 StatusBar = GameTooltipStatusBar {
 }
 SetLootCurrency = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:439
 SetSlottedKeystone = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:439
 SetWorldCursor = <function> defined @Interface/FrameXML/GameTooltip.lua:943
 SetLootItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:439
 SetMerchantCostItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:439
 GetUnit = <function> defined @Interface/FrameXML/GameTooltip.lua:985
 SetOwnedItemByID = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:439
 SetItemInteractionItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:439
 SetQuestLogSpecialItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:439
 TextRight1 = GameTooltipTextRight1 {
 }
 SetEnhancedConduit = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:439
 SetRecipeReagentItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:439
 SetQuestCurrency = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:439
 supportsDataRefresh = true
 SetWeeklyReward = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:439
 SetMerchantItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:439
 SetPvpBrawl = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:439
 SetAchievementByID = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:439
 BottomOverlay = Texture {
 }
 SetSpellByID = <function> defined =[C]:-1
 supportsItemComparison = true
 SetSocketedRelic = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:439
 ProcessInfo = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:235
 ProcessLines = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:288
 NineSlice = Frame {
 }
 SetInventoryItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:439
 RefreshData = <function> defined @Interface/FrameXML/GameTooltip.lua:924
 SetTransmogrifyItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:439
 SetLootRollItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:439
 SetQuestLogCurrency = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:439
 SetUnitDebuffByAuraInstanceID = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:439
 SetBagItem = <function> defined =[C]:-1
 GetSpell = <function> defined @Interface/FrameXML/GameTooltip.lua:981
 SetAction = <funct

**Comment by Stanzilla** [comment]
On which WoW version?

**Comment by teyasio** [comment]
PTR works fine, beta does not
